-- ============================================================
-- database/init.sql
--
-- PURPOSE: Initialize the PostgreSQL database on first start.
-- Docker runs this automatically when the postgres container
-- starts for the very first time (via docker-entrypoint-initdb.d/).
--
-- BEGINNER CONCEPT — What is SQL?
-- SQL (Structured Query Language) is how you talk to relational
-- databases. Commands include:
--   CREATE TABLE  → define a new table structure
--   INSERT INTO   → add rows of data
--   SELECT        → retrieve data
--   UPDATE        → modify existing rows
--   DELETE        → remove rows
--
-- This file only runs ONCE (on fresh database creation).
-- After that, use Alembic migrations for schema changes.
-- ============================================================

-- Set timezone to UTC for consistent timestamps across all regions
SET timezone = 'UTC';

-- ── Enable Extensions ────────────────────────────────────────
-- PostgreSQL extensions add extra functionality

-- uuid-ossp: generate UUID values in SQL
-- Lets us do: DEFAULT uuid_generate_v4() in column definitions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- pg_trgm: trigram-based text search (useful for fuzzy keyword search)
-- Lets us do fast LIKE queries: WHERE text LIKE '%revenue%'
CREATE EXTENSION IF NOT EXISTS "pg_trgm";


-- ── Table: chunks ─────────────────────────────────────────────
-- Stores metadata for every processed document chunk.
-- The actual vector embeddings live in Qdrant, not here.

CREATE TABLE IF NOT EXISTS chunks (
    chunk_id        VARCHAR(255)    PRIMARY KEY,
    text            TEXT            NOT NULL,
    source          VARCHAR(500)    NOT NULL,
    source_type     VARCHAR(50)     DEFAULT 'document',
    file_type       VARCHAR(20)     DEFAULT '',
    section_title   VARCHAR(500)    DEFAULT '',
    chunk_type      VARCHAR(50)     DEFAULT 'text',
    chunk_index     INTEGER         DEFAULT 0,
    total_chunks    INTEGER         DEFAULT 1,
    summary         TEXT            DEFAULT '',
    keywords        JSONB           DEFAULT '[]',    -- JSONB = binary JSON (faster queries)
    created_at      TIMESTAMPTZ     DEFAULT NOW()    -- TIMESTAMPTZ = timestamp with timezone
);

-- Index on source: fast lookup of all chunks from a specific file
-- "CREATE INDEX IF NOT EXISTS" = only create if it doesn't exist yet
CREATE INDEX IF NOT EXISTS idx_chunks_source ON chunks(source);

-- Index on source_type: fast filtering by document/code/image
CREATE INDEX IF NOT EXISTS idx_chunks_source_type ON chunks(source_type);

-- Trigram index for fast keyword search in chunk text
-- Enables fast: WHERE text ILIKE '%revenue growth%'
CREATE INDEX IF NOT EXISTS idx_chunks_text_trgm
    ON chunks USING gin(text gin_trgm_ops);

-- ── Table: answers ────────────────────────────────────────────
-- Every query-answer pair generated by the system.

CREATE TABLE IF NOT EXISTS answers (
    answer_id           VARCHAR(255)    PRIMARY KEY,
    query_id            VARCHAR(255)    NOT NULL,
    query_text          TEXT            NOT NULL,
    answer_text         TEXT            NOT NULL,
    sources             JSONB           DEFAULT '[]',
    confidence_score    FLOAT           DEFAULT 0.0,
    evaluation_score    FLOAT,                          -- NULL until evaluated
    approved_by_human   BOOLEAN         DEFAULT FALSE,
    route_taken         VARCHAR(50)     DEFAULT 'direct',
    latency_ms          INTEGER,
    token_count         INTEGER,
    timestamp           TIMESTAMPTZ     DEFAULT NOW()
);

-- Index on timestamp: fast retrieval of recent answers
CREATE INDEX IF NOT EXISTS idx_answers_timestamp ON answers(timestamp DESC);

-- Index on evaluation_score: fast filtering for low-scored answers
CREATE INDEX IF NOT EXISTS idx_answers_eval_score ON answers(evaluation_score);

-- ── Table: evaluations ───────────────────────────────────────
-- LLM Judge scores for each answer.
-- Separate from answers so one answer can be re-evaluated multiple times.

CREATE TABLE IF NOT EXISTS evaluations (
    eval_id             VARCHAR(255)    PRIMARY KEY,
    answer_id           VARCHAR(255)    NOT NULL
                            REFERENCES answers(answer_id) ON DELETE CASCADE,
                            -- ON DELETE CASCADE: delete evaluation when answer is deleted
    relevance_score     FLOAT           DEFAULT 0.0
                            CHECK (relevance_score BETWEEN 0 AND 10),
                            -- CHECK constraint: enforces value range at database level
    accuracy_score      FLOAT           DEFAULT 0.0
                            CHECK (accuracy_score BETWEEN 0 AND 10),
    completeness_score  FLOAT           DEFAULT 0.0
                            CHECK (completeness_score BETWEEN 0 AND 10),
    clarity_score       FLOAT           DEFAULT 0.0
                            CHECK (clarity_score BETWEEN 0 AND 10),
    overall_score       FLOAT           DEFAULT 0.0
                            CHECK (overall_score BETWEEN 0 AND 10),
    judge_reasoning     TEXT            DEFAULT '',
    timestamp           TIMESTAMPTZ     DEFAULT NOW()
);

-- Index: fast lookup of evaluations for a specific answer
CREATE INDEX IF NOT EXISTS idx_eval_answer_id ON evaluations(answer_id);

-- Index: fast filtering by overall score (for feedback loop)
CREATE INDEX IF NOT EXISTS idx_eval_overall_score ON evaluations(overall_score);

-- ── Table: feedback ───────────────────────────────────────────
-- Improvement signals generated by the feedback loop.
-- The Planner reads these to learn from past mistakes.

CREATE TABLE IF NOT EXISTS feedback (
    feedback_id     VARCHAR(255)    PRIMARY KEY,
    source          VARCHAR(50)     NOT NULL,           -- 'evaluation' or 'human'
    issue_type      VARCHAR(100)    NOT NULL,           -- 'accuracy', 'relevance', etc.
    details         TEXT            DEFAULT '',
    original_query  TEXT            NOT NULL,
    suggested_fix   TEXT            DEFAULT '',
    timestamp       TIMESTAMPTZ     DEFAULT NOW()
);

-- Index: fast filtering by issue type (to see which problems are most common)
CREATE INDEX IF NOT EXISTS idx_feedback_issue_type ON feedback(issue_type);

-- Index: chronological ordering for the feedback buffer
CREATE INDEX IF NOT EXISTS idx_feedback_timestamp ON feedback(timestamp DESC);


-- ── VIEWS (pre-built queries for common lookups) ──────────────

-- View: answers with their evaluation scores joined together
-- Usage: SELECT * FROM answers_with_scores WHERE overall_score < 7;
CREATE OR REPLACE VIEW answers_with_scores AS
    SELECT
        a.answer_id,
        a.query_text,
        a.answer_text,
        a.route_taken,
        a.latency_ms,
        a.timestamp,
        e.relevance_score,
        e.accuracy_score,
        e.completeness_score,
        e.clarity_score,
        e.overall_score,
        e.judge_reasoning
    FROM answers a
    LEFT JOIN evaluations e ON a.answer_id = e.answer_id;

-- View: daily performance summary
-- Usage: SELECT * FROM daily_stats ORDER BY day DESC LIMIT 7;
CREATE OR REPLACE VIEW daily_stats AS
    SELECT
        DATE(a.timestamp)               AS day,
        COUNT(*)                        AS total_answers,
        AVG(e.overall_score)            AS avg_score,
        AVG(a.latency_ms)               AS avg_latency_ms,
        COUNT(*) FILTER (WHERE e.overall_score < 7)  AS low_score_count,
        COUNT(*) FILTER (WHERE a.approved_by_human)  AS human_approved_count
    FROM answers a
    LEFT JOIN evaluations e ON a.answer_id = e.answer_id
    GROUP BY DATE(a.timestamp);

-- ── SEED DATA (example test data) ────────────────────────────
-- Only insert if the table is completely empty (first run only)
-- BEGINNER CONCEPT — INSERT INTO ... WHERE NOT EXISTS:
-- This pattern safely inserts data only once.

INSERT INTO chunks (chunk_id, text, source, source_type, summary, keywords)
SELECT
    'seed_chunk_001',
    'This is a sample document chunk for testing purposes. The advanced RAG system is now running.',
    'system/seed.txt',
    'document',
    'Sample seed chunk for system verification.',
    '["sample", "seed", "testing", "rag"]'::jsonb
WHERE NOT EXISTS (
    SELECT 1 FROM chunks WHERE chunk_id = 'seed_chunk_001'
);

-- Log that initialization completed
DO $$
BEGIN
    RAISE NOTICE 'Database initialization complete. Tables created: chunks, answers, evaluations, feedback.';
END $$;
